version: '3'

services:
  redis-db:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - ./../redis-data:/data
    networks:
      - mern-network      
    depends_on:
      - database  

  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      -  NODE_ENV=production
    depends_on:
      - redis-db  
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./../mongo-data:/data/db
    networks:
      - mern-network    

networks:
  mern-network:
    driver: bridge      
