
export const products = [
  {
    name: "Kid Tapered Slim Fit Trouser",
    price: 38,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/lwwsm4wnlnqseez439dc.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/lwwsm4wnlnqseez439dc.png", "", "", ""],
    category: "Kids",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 64,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/hevv2optwbd8yrczb1zm.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/hevv2optwbd8yrczb1zm.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 60,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/petfkuxhsd0q29kez1qg.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/petfkuxhsd0q29kez1qg.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 74,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/gdhtrzose3vkgmbuvyrt.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/gdhtrzose3vkgmbuvyrt.png", "", "", ""],
    category: "Women",
    subCategory: "Winterwear",
    isBestseller: false,
  },
  {
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 58,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/cmmardozfuajvup3j5x6.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/cmmardozfuajvup3j5x6.png", "", "", ""],
    category: "Men",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 56,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/bkkc86d5909l1vide2jk.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/bkkc86d5909l1vide2jk.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 68,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/n3eidycjryupybquufpe.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/n3eidycjryupybquufpe.png", "", "", ""],
    category: "Women",
    subCategory: "Winterwear",
    isBestseller: true,
  },
  {
    name: "Kid Tapered Slim Fit Trouser",
    price: 40,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fttfx12yjuwrbxct4fjp.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fttfx12yjuwrbxct4fjp.png", "", "", ""],
    category: "Kids",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Men Printed Plain Cotton Shirt",
    price: 52,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/zkbuvtxwt0xsiiszxtd3.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/zkbuvtxwt0xsiiszxtd3.png", "", "", ""],
    category: "Men",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 78,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/krgrlpvy4ktlkbdfyxsv.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/krgrlpvy4ktlkbdfyxsv.png", "", "", ""],
    category: "Women",
    subCategory: "Winterwear",
    isBestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 79,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/kgskxuyqth8vmsn05u0k.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/kgskxuyqth8vmsn05u0k.png", "", "", ""],
    category: "Men",
    subCategory: "Winterwear",
    isBestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 82,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/mdt65bfzibn8h8b61kks.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/mdt65bfzibn8h8b61kks.png", "", "", ""],
    category: "Women",
    subCategory: "Winterwear",
    isBestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 30,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/njgv6holzbqubpdrixfq.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/njgv6holzbqubpdrixfq.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 26,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/nbx5rbjtaxxdxlwxrql2.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/nbx5rbjtaxxdxlwxrql2.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 40,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/e7ncuixgwvz2ycefd1bz.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/e7ncuixgwvz2ycefd1bz.png", "", "", ""],
    category: "Women",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 38,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/nfacnbbpjnfq2xxtolo9.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/nfacnbbpjnfq2xxtolo9.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 72,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/uld8cfm8bebjxhi1rtkk.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/uld8cfm8bebjxhi1rtkk.png", "", "", ""],
    category: "Men",
    subCategory: "Winterwear",
    isBestseller: true,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 82,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/kfk7m9rbkmcchuqswicf.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/kfk7m9rbkmcchuqswicf.png", "", "", ""],
    category: "Women",
    subCategory: "Winterwear",
    isBestseller: false,
  },
  {
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 63,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/kxeazuykw1obk3zrsshz.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/kxeazuykw1obk3zrsshz.png", "", "", ""],
    category: "Men",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 26,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/dgyyfdv4iejb58ovia8x.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/dgyyfdv4iejb58ovia8x.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 68,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/lcn34m1buoeuhh14cqlj.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/lcn34m1buoeuhh14cqlj.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 28,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/rcrpgmz1wytibuhbndpy.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/rcrpgmz1wytibuhbndpy.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 38,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/pq5jbkbdfrh94fqhvfld.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/pq5jbkbdfrh94fqhvfld.png", "", "", ""],
    category: "Women",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 80,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/sigt4rcrmlpq5a2gsl8t.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/sigt4rcrmlpq5a2gsl8t.png", "", "", ""],
    category: "Men",
    subCategory: "Winterwear",
    isBestseller: false,
  },
  {
    name: "Kid Tapered Slim Fit Trouser",
    price: 60,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/gftmg5iayxpqp7jzqm3x.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/gftmg5iayxpqp7jzqm3x.png", "", "", ""],
    category: "Kids",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 42,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/vtrzs1ouqhdqmkcutvid.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/vtrzs1ouqhdqmkcutvid.png", "", "", ""],
    category: "Women",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 34,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/hky1xj1jpk6hxvyf4aqj.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/hky1xj1jpk6hxvyf4aqj.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 40,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/uq75tn4dzht8ngkdtoww.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/uq75tn4dzht8ngkdtoww.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 45,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/gfjfu2ym2tkynu0rseuy.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/gfjfu2ym2tkynu0rseuy.png", "", "", ""],
    category: "Women",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Palazzo Pants with Waist Belt",
    price: 67,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/ohgwk6y8khmhvyzfmrei.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/ohgwk6y8khmhvyzfmrei.png", "", "", ""],
    category: "Women",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 50,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/phf5jv1gxhyiesocewby.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/phf5jv1gxhyiesocewby.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 84,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/qrs4oi8czhn3xutplecl.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/qrs4oi8czhn3xutplecl.png", "", "", ""],
    category: "Men",
    subCategory: "Winterwear",
    isBestseller: true,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 48,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/m62p3halntslyrtkqbul.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/m62p3halntslyrtkqbul.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 78,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/vf9pdof7kque73qgqnyy.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/vf9pdof7kque73qgqnyy.png", "", "", ""],
    category: "Women",
    subCategory: "Winterwear",
    isBestseller: true,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 48,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fv5wduuhtf3ohwvqtkke.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fv5wduuhtf3ohwvqtkke.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 46,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/wlp3zppdhuk3hceai00f.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/wlp3zppdhuk3hceai00f.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 42,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/zus6k9qkekf5ytkcupsv.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/zus6k9qkekf5ytkcupsv.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 36,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fjizfkmwvbsmtsm9pttd.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fjizfkmwvbsmtsm9pttd.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 60,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/rgbfwjo6ttsxwvqnvuhi.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/rgbfwjo6ttsxwvqnvuhi.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 54,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/zimxmcw6cbuuolotsykx.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/zimxmcw6cbuuolotsykx.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Palazzo Pants with Waist Belt",
    price: 52,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/vzbastjtehm9f4vc2rzf.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/vzbastjtehm9f4vc2rzf.png", "", "", ""],
    category: "Women",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 64,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fhjhti4bq4cn40ulzhbv.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fhjhti4bq4cn40ulzhbv.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 25,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/spm2rc1h5fnukbxdsz8u.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/spm2rc1h5fnukbxdsz8u.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 77,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/no7tqmxukr2cpmrktrxz.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/no7tqmxukr2cpmrktrxz.png", "", "", ""],
    category: "Men",
    subCategory: "Winterwear",
    isBestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 26,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/kfft5y5qitqhpgp1wphi.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/kfft5y5qitqhpgp1wphi.png", "", "", ""],
    category: "Kids",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Kid Tapered Slim Fit Trouser",
    price: 56,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fqpp9modvx1x9uommsae.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/fqpp9modvx1x9uommsae.png", "", "", ""],
    category: "Kids",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 86,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/zv9odi15o0zwp943pagh.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/zv9odi15o0zwp943pagh.png", "", "", ""],
    category: "Men",
    subCategory: "Winterwear",
    isBestseller: true,
  },
  {
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 70,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/gxstjfl0sthgzgopkewk.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/gxstjfl0sthgzgopkewk.png", "", "", ""],
    category: "Men",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 30,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/siuifxikwfbu84jmouhd.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/siuifxikwfbu84jmouhd.png", "", "", ""],
    category: "Women",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 36,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/s8g0zlctiwkmvcjggp0s.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/s8g0zlctiwkmvcjggp0s.png", "", "", ""],
    category: "Women",
    subCategory: "Topwear",
    isBestseller: false,
  },
  {
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 72,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/isdyb8ehbvffgiqjdq0b.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/isdyb8ehbvffgiqjdq0b.png", "", "", ""],
    category: "Men",
    subCategory: "Bottomwear",
    isBestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 80,
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    sizes: ["SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE"],
    image: "https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/viktgbxgny4tjjtqqyny.png",
    subImages: ["https://res.cloudinary.com/dgtqdbaez/image/upload/v1737840118/mern-e-commerce-products-images/viktgbxgny4tjjtqqyny.png", "", "", ""],
    category: "Men",
    subCategory: "Topwear",
    isBestseller: false,
  },
];
